security:
    # encoders:
    #     SfDay\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        secured_area:
            pattern:    ^/
            logout:     true
            form_login:
                provider: fos_userbundle
            anonymous:  ~
            # http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/post/new, roles: ROLE_BLOGGER }
        - { path: ^/post/create, roles: ROLE_BLOGGER }
        - { path: ^/post/[\d+]/edit, roles: ROLE_BLOGGER }
        - { path: ^/post/[\d+]/update, roles: ROLE_BLOGGER }
        - { path: ^/post/[\d+]/delete, roles: ROLE_BLOGGER }
        - { path: ^/post$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

